---
#- name: pull docker image
#  shell: "docker pull {{ docker_registry }}/logstash-es:v1.0.0"

#- name: stop running containers
#  shell: "docker stop $(docker ps | grep -E 'logstash|logstash-es' | cut -d' ' -f 1) || true"

#- name: remove stopped containers
#  shell: "docker rm $(docker ps -a | grep -E 'logstash|logstash-es' | cut -d' ' -f 1) || true"

- name: deploy logstash
  docker_container:
    api_version: 1.19
    name: logstash-es
    hostname: "{{ inventory_hostname }}"
    image: "{{ docker_registry }}/{{ logstash_image }}:{{ logstash_image_tag }}"
    state: started 
    network_mode: host
    privileged: yes
    exposed_ports: 9000 #placeholder as it fails with NoneType
    env:
      ES_SERVER: "{{ elasticsearch_server }}"
      ES_PORT: "{{ elasticsearch_port }}"
      INPUT_SYSLOG: "true"
      INPUT_POSTGRESQL: "true"
      INPUT_TOMCAT: "true"
      INPUT_KAFKA: "true"
      INPUT_HBASE: "true"
      INPUT_SPARK: "true"
      INPUT_SPARKOFFSET: "true"
      OUTPUT_ELASTIC: "true"
    pull: yes 
    restart_policy: always
    volumes: "{{ volumes }}"
